### ISSUE TITLE
GitHub Actions DocTest failing

### ISSUE THREAD

**Issue by Sudraka** [kowainik/learn4haskell#109]
It seems like, despite the local tests passing for my chapter 1 solutions, the Github actions are failing.

Here's the more detailed log.

https://github.com/Sudraka/learn4haskell/runs/1210777764

**Comment by chshersh** [comment]
@Sudraka Sorry for your experience :disappointed: CI can produce unreliable results sometimes. Try restarting the workflow. The problem may disappear in consequent runs.

**Comment by chshersh** [comment]
@Sudraka I'm going to close this issue, as Doctest work so far. So I would blame just a random non-reproducible bug. Let us know if you have any other issues :slightly_smiling_face:
