### ISSUE TITLE
README.md: *boiling

### ISSUE THREAD

**Issue by kodaj** [kowainik/learn4haskell#167]
It looks like there's a typo in README.md: "...people are contributing to projects within the communities they are
__boiling__ in."  Are you sure you wanted to use the verb "boil" here? I mean, I can imagine that tempers can flare  up sometimes in programming communities, but I never thought the temperature would reach boiling point ;)

**Comment by vrom911** [comment]
Haha, nice catch! Believe me, it is possible to boil 😸 
But, I see now that this is not a phrase in English. I probably just translated from my mother language, where it makes more sense 😄 
What I wanted to say is that "they contribute to the communities they are spending most of their time already and not trying to go out those boundaries". Sorry for such confusion!
