### ISSUE TITLE
Unable to open pull request for Chapter 4

### ISSUE THREAD

**Issue by pastoreerrante** [kowainik/learn4haskell#354]
Dumb question, guys.

Somehow I'm unable to open the last pull request. 

On my forked repo I can see the latest commit, with Chapter 4 solutions. Then, if I open the "create a pull request" link I can't see the usual embedded editor from which I can add a description and then open the pull request.

Any ideas? Thanks

**Comment by chshersh** [comment]
@pastoreerrante I'm not sure either. But my guess would be is the fact that all your solutions are implemented in the `master` branch, and you currently already have a PR open from the `master` branch.

* https://github.com/kowainik/learn4haskell/pull/342

 It seems you can't have multiple PRs open from the same branch at the same time. I can recommend trying to close your current PR and open a new one with the solutions to Chapter 4.

**Comment by pastoreerrante** [comment]
good catch. I was finally able to open the final pull request. Thanks!
