### ISSUE TITLE
doctest failed

### ISSUE THREAD

**Issue by juev** [kowainik/learn4haskell#36]
I have [solutions](https://github.com/juev/learn4haskell/commit/55c772f628982fff6c6ae55e25322bf63f605e41) for Chapter1.

```haskell
Test suite doctest-chapter1: RUNNING...
src/Chapter1.hs:298: failure in expression `1 + 2'
expected: 3
          it :: Num a => a
 but got: 3
          ^
```

but I have in code:
```haskell
>>> 1 + 2
3
it :: Num a => a
>>> 10 - 15
```

Something wrong...

**Comment by chshersh** [comment]
Hi @juev! Our doctest tests don't expect the line `it :: Num a => a` and similar ones. By default, GHCi doesn't print the type of each expression. You probably enabled this option in GHCi somehow (either explicitly or implicitly from some GHCi config file) by running the `:set +t` command. When inserting answers to GHCi, you either need to insert everything before the `it :: ...` line, or execute the `:unset +t` command after entering GHCi to avoid seeing this line.

Hope this helps! Let us know if the problem still persists.

**Comment by juev** [comment]
Ok, thank you!
I forgot about my .ghci settings. 😕
