### ISSUE TITLE
Main project description

### ISSUE THREAD

**Issue by vrom911** [kowainik/learn4haskell#5]
- [ ] What is it
- [ ] Goals
- [ ] Is it suitable for you?
- [ ] How to participate
- [ ] How to open PRs and ask our review
- [ ] ???

**Comment by premkiran7** [comment]
@vrom911 I am confused as README was not helpful and I saw the hacktoberfest label on the repo. Can I work on any issue 
here?

**Comment by vrom911** [comment]
Hey @premkiran7 ! Thanks for your interest. We are in the process of updating the information in this course and in README as well. Once it is done, you could see how you would be able to participate in this project. It will be finished by the 1st of October, so don't worry 🙂
