### ISSUE TITLE
Save @vrom911's and @chshersh's time by including solutions

### ISSUE THREAD

**Issue by bitwombat** [kowainik/learn4haskell#506]
Thank you @vrom911 and @chshersh for this fun course! Just the right difficulty level for a 'confidence building' break from Haskell Programming From First Principles.

I'm finding myself searching through PRs to see solutions - sometimes I need a hint, and sometimes I just want to see other solutions, or what you've said to others.

Instead of you reviewing many PRs with the same basic solutions, many of us could review our own if there was a set of solutions provided - maybe even just taken from a PR you thought had the best solutions?

Thank you again for all the work you've put into this.

**Comment by chshersh** [comment]
Hi @bitwombat 👋🏻 

We actually already have all the solutions for all tasks. Check other branches in this repository:

* https://github.com/kowainik/learn4haskell/branches

So you can choose a branch for a chapter you're currently working at and check the solutions 🙂
